#+TODO: TODO IN-PROGRESS DONE
* training-planner
Yksinkertainen harjoitusohjelman luomiseen tarkoitettu
työkalu. Tarkoituksena on helpottaa viikko-ohjelman syöttämistä
kalenteriin. Peruspuutteena kalenteriohjelmissa on, ettei yksittäistä
merkintää voi helposti kopioida. Tämä vaikeuttaa peruslenkkien
syöttämistä kalenteriin.
* Käyttö
-  Syötä harjotuksia ja laita ne paikalleen hiirellä. Jos painat CTRL
pohjaan ennen harjoituksen raahaamista, harjoitus kopioituu. Näin on
helppo syöttää useita samanlaisia harjoituksia.
- Lataa harjoitukset ical muodossa ja importtaa haluamaasi
  kalenteriin. Tässä vaiheessa voit säätää lopulliset ajat
  kohdilleen.
* Suunnitteilla olevia toimintoja
** TODO Renderöi harjoitus paremmin
Ainakin se tulisi rivittää oikein
** TODO Useamman viikon ohjelman tekeminen kerralla
 Jos haluan tehdä useamman viikon ohjelman kerralla, haluan luultavasti
 vaihdella viikkoja tai ehkä nähdä niitä useamman kerralla
** TODO Yhteenvedon laskeminen
- Harjoituksen pituus pitää saada pääteltyä harjoituksesta, muuten
  näiden syöttäminen menee hankalaksi
- jos se ei arvaa oikein, voisi pituuden syöttää käsin
