* training-planner
Yksinkertainen harjoitusohjelman luomiseen tarkoitettu
työkalu. Tarkoituksena on helpottaa viikko-ohjelman syöttämistä
kalenteriin. Peruspuutteena kalenteriohjelmissa on, ettei yksittäistä
merkintää voi helposti kopioida. Tämä vaikeuttaa peruslenkkien
syöttämistä kalenteriin.
* Käyttö
-  Syötä harjotuksia ja laita ne paikalleen hiirellä. Jos painat CTRL
pohjaan ennen harjoituksen raahaamista, harjoitus kopioituu. Näin on
helppo syöttää useita samanlaisia harjoituksia.
- Lataa harjoitukset ical muodossa ja importtaa haluamaasi
  kalenteriin. Tässä vaiheessa voit säätää lopulliset ajat
  kohdilleen.
* Suunnitteilla olevia toimintoja
** TODO Harjoituksien lataaminen ical formaatissa
 Tämän voi tehdä browserissa käyttämällä data-formaatin a hreffiä
 esim
 https://ourcodeworld.com/articles/read/189/how-to-create-a-file-and-generate-a-download-with-javascript-in-the-browser-without-a-server
** TODO Viikon vaihtaminen
** TODO Useamman viikon ohjelman tekeminen kerralla
 Jos haluan tehdä useamman viikon ohjelman kerralla, haluan luultavasti
 vaihdella viikkoja tai ehkä nähdä niitä useamman kerralla
** TODO Useamman rivin harjoitus
- eka rivi on title
- loput descriptionia
** TODO Harjoituksen muokkaaminen
- valittu harjoitus tulisi editoriin ja se muokkaisi harjoitusta
- kokeiltava tuleeko tästä hämminkiä
